<?xml version="1.0"?>
<robot name = "arm" xmlns:xacro= "https://www.ros.org/wiki/xacro">




    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name= "arm_cylinder_radius" value = "0.02"/>
    <xacro:property name= "arm_cylinder_length" value = "0.3"/>


    


    <link name="arm_base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.5" x="${arm_base_length}" y="${arm_base_width}" z="${arm_base_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>





    <link name="forearm_link">
        <visual>
            <origin xyz="0 0 ${arm_cylinder_length / 2.0}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${arm_cylinder_radius}" length="${arm_cylinder_length}" /> 
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${arm_cylinder_length / 2.0}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${arm_cylinder_radius}" length="${arm_cylinder_length}" /> 
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${arm_cylinder_radius}" l="${arm_cylinder_length}" 
                           o_xyz="0 0 ${arm_cylinder_length / 2.0}" o_rpy="0 0 0" />
    </link>


    <link name="hand_link">
        <visual>
            <origin xyz="0 0 ${arm_cylinder_length / 2.0}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${arm_cylinder_radius}" length="${arm_cylinder_length}" /> 
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${arm_cylinder_length / 2.0}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${arm_cylinder_radius}" length="${arm_cylinder_length}" /> 
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${arm_cylinder_radius}" l="${arm_cylinder_length}" 
                           o_xyz="0 0 ${arm_cylinder_length / 2.0}" o_rpy="0 0 0" />
    </link>




    <joint name="base_forearm" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100" />
        <dynamics friction = "0.3" damping = "0.3"/>
    </joint>


        <joint name="forearm_hand" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${arm_cylinder_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100" />
        <dynamics friction = "0.3" damping = "0.3"/>
    </joint>

    <joint name="arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="0 0 ${(base_height) + (arm_base_height)/2.0} " rpy="0 0 0" />
    </joint>
</robot >
